site_name: Gitsheets Documentation
site_description: Gitsheets is the toolkit for distributed recordkeeping that lives inside Git
site_author: Jarvus Innovations
copyright: 2020 Jarvus Innovations
repo_url: https://github.com/JarvusInnovations/gitsheets
edit_uri: edit/master/docs

theme:
  name: material
  features:
    - navigation.tabs
  palette:
    primary: "orange"
    accent: "deep purple"

plugins:
  - search
  - awesome-pages

extra_javascript:
  - https://unpkg.com/mermaid@8.5.0/dist/mermaid.min.js

extra_css:
  - https://use.fontawesome.com/releases/v5.13.0/css/all.css

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: '!!python/name:pymdownx.superfences.fence_div_format'
  - pymdownx.smartsymbols
  - meta
  - toc:
      # insert a blank space before the character
      permalink: " ¶"
  - smarty
  - fontawesome_markdown
  - mdx_truly_sane_lists
